### ISSUE TITLE
add home-brew tap

### ISSUE THREAD

**Issue by FalcoSuessgott** [FalcoSuessgott/vkv#296]
https://goreleaser.com/customization/homebrew/?h=brew#limitations
```
brews:
  - repository:
      owner: vkv
      name: homebrew-tap
    directory: Formula
    goarm: "7"
    homepage: https://github.com/FalcoSuessgott/vkv
    description: vkv enables you to list, compare, move, import, document, backup & encrypt secrets from a HashiCorp Vault KV engine
    license: MIT
    test: |
      system "#{bin}/vkv -v"
    dependencies:
      - name: go
        type: optional
    extra_install: |-
      bash_completion.install "completions/vkv.bash" => "vkv"
      zsh_completion.install "completions/vkv.zsh" => "_vkv"
      fish_completion.install "completions/vkv.fish"
      man1.install "manpages/vkv.1.gz"
```
